### ISSUE TITLE
EEPROM address conflict for axiom & odometer?

### ISSUE THREAD

**Issue by trosenband** [vedderb/bldc#307]
There seems to be a conflict at EEPROM address 1 (as of commit be439a2):  

`datatypes.h:1150:#define EEPROM_ADDR_ODOMETER    1`
`hwconf/hw_axiom.c:58:#define EEPROM_ADDR_CURRENT_GAIN	0`
`hwconf/hw_axiom.c:59:#define EEPROM_ADDR_INPUT_CURRENT_GAIN	1`

To avoid future issues, perhaps all EEPROM_ADDR values should be defined in one place (e.g. eeprom.h)?

[I had added the odometer](https://github.com/vedderb/bldc/pull/218) when EEPROM_ADDR_INPUT_CURRENT_GAIN did not yet exist on my branch.

**Comment by vedderb** [comment]
That PR is a hw-specific update, so it is both in the dev-branch and in master. The dev-branch is quite far ahead of master now, but I'm aiming to merge it after doing some more testing. More or less everything I wanted to get into that release is there now.

This should be fixed in this commit, which also make the odometer persistent between firmware updates:
https://github.com/vedderb/bldc/commit/55dba9a79d7f84cd914789e020b10eaed4e95465
That commit also sets up a structure for adding more persistent data (between reboots and firmware updates) to the firmware by adding it to the end of the backup_data struct.

The intention of _conf\_general\_[read/store]\_eeprom\_var\_hw_ is to be used by the hwconf only, as axiom did, so the should not be conflicts if that is done. Likewise, _conf\_general\_[read/store]\_eeprom\_var\_custom_ is intended to be used by custom apps only.
