### ISSUE TITLE
ADC inconsistency in current double sampling mode

### ISSUE THREAD

**Issue by Guillaume227** [vedderb/bldc#309]
It seems to me, based on how ADC channels are setup in **hw_setup_adc_channels**(), that currents samples should be taken from the same ADC in **mcpwm_adc_inj_int_handler**.
```	// Injected channels
	ADC_InjectedChannelConfig(ADC1, ADC_Channel_10, 1, ADC_SampleTime_15Cycles);
	ADC_InjectedChannelConfig(ADC2, ADC_Channel_11, 1, ADC_SampleTime_15Cycles);
	ADC_InjectedChannelConfig(ADC3, ADC_Channel_12, 1, ADC_SampleTime_15Cycles);
	ADC_InjectedChannelConfig(ADC1, ADC_Channel_10, 2, ADC_SampleTime_15Cycles);
	ADC_InjectedChannelConfig(ADC2, ADC_Channel_11, 2, ADC_SampleTime_15Cycles);
	ADC_InjectedChannelConfig(ADC3, ADC_Channel_12, 2, ADC_SampleTime_15Cycles);
	ADC_InjectedChannelConfig(ADC1, ADC_Channel_10, 3, ADC_SampleTime_15Cycles);
	ADC_InjectedChannelConfig(ADC2, ADC_Channel_11, 3, ADC_SampleTime_15Cycles);
	ADC_InjectedChannelConfig(ADC3, ADC_Channel_12, 3, ADC_SampleTime_15Cycles);
```

However I see curr0 taken from ADC1 and curr0_2 taken from ADC2 while it's the opposite for curr1 and curr1_2. 
```
	int curr0 = ADC_GetInjectedConversionValue(ADC1, ADC_InjectedChannel_1);
	int curr1 = ADC_GetInjectedConversionValue(ADC2, ADC_InjectedChannel_1);

	int curr0_2 = ADC_GetInjectedConversionValue(ADC2, ADC_InjectedChannel_2);
	int curr1_2 = ADC_GetInjectedConversionValue(ADC1, ADC_InjectedChannel_2);

```

Am I missing something or is it just that it's not a widely used feature that hasn't received a lot of attention?

**Comment by myLens** [comment]
To me the configuration of the injected channels seems ridiculous. I don't know what is being used as trigger event but the author might have a look @ AN4195 to better understand ADC conversion in ARM-4 architecture.

**Comment by Guillaume227** [comment]
What qualifies as ridiculous, could you provide more details, I am curious?
One thing that also doesn't make sense to me in that are is that it's setup as an injected sequence of length 3 even tough the rest of the code only averages on 2 samples - so the 3rd sample is unused.

**Comment by myLens** [comment]
Well having all 3 ADC's injection scan the same 3 channels has to be a very special trick or completely senseless.
One uses ADC injection to get a ADC measurement at a very specific moment. One ADC converter (e.g ADC1 or 2 or 3) could do this job. Sorry I don't know the rest of the source code and if the ADC result is read in the ADC_IRQHandler ISR which i assume.
In such ADC_IT_JEOC ("End of injected group conversion") would indicate completion of injected conversion on each of the 3 ADC individually. So now it depends when injected conversion was triggered for each of the three ADC's. They would then come up one after the other having read all three channels. If the reason was to average all three results you would have to look at the code but imo averaging this way would not be state of the art. So check when injected conversion is started for each of the 3 ADC's which might bring light into the dark. BR, Tom

**Comment by myLens** [comment]
CH_IRQ_HANDLER(ADC1_2_3_IRQHandler) {
        	CH_IRQ_PROLOGUE();
        	ADC_ClearITPendingBit(ADC1, ADC_IT_JEOC);
        	mc_interface_adc_inj_int_handler();
        	CH_IRQ_EPILOGUE();
}
It seems to me that interrupt is only enabled for ADC1 and the author expects that all ADC's have finished together with it. Seems they are all started at the same time and using  them three in parallel is based on the idea to average their result.
So it would be the same which ADC you get the result as one is as good (or bad) as the other. ADC3 could be used as well imo.

**Comment by myLens** [comment]
Well in ADC init DMA is used ??? Not clear to me and maybe some software evolution without cleaning up ?

**Comment by myLens** [comment]
Well you have the explanation here:
// Injected channels for current measurement at end of cycle
      
      
        	ADC_ExternalTrigInjectedConvConfig(ADC1, ADC_ExternalTrigInjecConv_T1_CC4);
      
      
        	ADC_ExternalTrigInjectedConvConfig(ADC2, ADC_ExternalTrigInjecConv_T8_CC2);
      
      
        #ifdef HW_HAS_3_SHUNTS
      
      
        	ADC_ExternalTrigInjectedConvConfig(ADC3, ADC_ExternalTrigInjecConv_T8_CC3);
      
      
        #endif
      
      
        	ADC_ExternalTrigInjectedConvEdgeConfig(ADC1, ADC_ExternalTrigInjecConvEdge_Falling);
      
      
        	ADC_ExternalTrigInjectedConvEdgeConfig(ADC2, ADC_ExternalTrigInjecConvEdge_Falling);
      
      
        #ifdef HW_HAS_3_SHUNTS
      
      
        	ADC_ExternalTrigInjectedConvEdgeConfig(ADC3, ADC_ExternalTrigInjecConvEdge_Falling);
      
      
        #endif
      
      
        	ADC_InjectedSequencerLengthConfig(ADC1, HW_ADC_INJ_CHANNELS);
      
      
        	ADC_InjectedSequencerLengthConfig(ADC2, HW_ADC_INJ_CHANNELS);
      
      
        #ifdef HW_HAS_3_SHUNTS
      
      
        	ADC_InjectedSequencerLengthConfig(ADC3, HW_ADC_INJ_CHANNELS);
      
      
        #endif
      
      
        

      
      
        	hw_setup_adc_channels();
      
      
        

      
      
        	// Interrupt
      
      
        	<span class="pl-c1">ADC_ITConfig</span>(ADC1, ADC_IT_JEOC, ENABLE);

The vectored and nonvectored versions are very different ;-)
But you see here that the 3 are triggered async, I am only wondering why the flags are not queried in the ISR and why ADC1 status shall be valid for all three ? Imo the JEOC flag has to be verified for each of the ADCs individually but maybe it is done somewhere. ADC3 is ued in 3 shunt version only as you can see.

**Comment by vedderb** [comment]
First, regular and injected channels are used at the same time so that different sampling points can be triggered in the PWM cycle in BLDC mode - one is more convenient for current and the other is more convenient for voltage. FOC only uses regular channels, as everything can be sampled at the same time.

The double sampling code is only used for two shunt hardware, and is a desperate attempt at dealing with the noise on the ADC channel that gets a really short sampling window on high modulation. With three shunts this problem does not exist as there always are two good reading to use regardless of the modulation, so that code is not used then.

The current sampling is triggered at the same time for all modes except bipolar mode, so when the first ADC finishes the others are done too. There is no need to clear their interrupt flag if you aren't using the interrupt. Bipolar mode has some cases where the samples will be off by one pwm cycle, which matters slightly on high motor speeds, but I didn't bother fixing that as bipolar pwm mode does not work that well anyway and isn't that useful.

In general the mcpwm code for six step commutation can be cleaned up a lot, but I have more or less just left it as it is years ago and focused on the FOC code instead. If I make any changes in it now I have to dig up old hardware and do a lot of testing to make sure that nothing broke, and that does not have high priority now.
