### ISSUE TITLE
[Coding error ?] interlinked loops with the same increment name

### ISSUE THREAD

**Issue by alexisthethe** [vedderb/bldc#36]
Hi Benjamin,

In this loop 1 (https://github.com/vedderb/bldc/blob/master/mcpwm_foc.c#L881) and this loop 2 (https://github.com/vedderb/bldc/blob/master/mcpwm_foc.c#L884)
the increment "i" is the same !!!

Afterwards in the loop 1 there is a condition on "i" (https://github.com/vedderb/bldc/blob/master/mcpwm_foc.c#L902)
It seems logic it corresponds to the "i" of the loop 1 but as it is after the loop 2 is finished I think the condition takes the loop 2 "i" (float) value.

Is this an error ?

**Comment by vedderb** [comment]
This is not an error because C will always use the variable name in the closest scope. Also, a variable declared in one scope cannot be accessed from outside of that scope, so the condition will use i from the outer loop. It would be a problem if the inner loop needs to use i from the outer loop, but that is luckily not the case here. I do agree that using different names for the indexes makes the code a bit more clear though.
