### ISSUE TITLE
possible error in mc_interface.c?

### ISSUE THREAD

**Issue by derlucas** [vedderb/bldc#45]
is this an error? maybe i read it wrong but i think the lo_max_rpm variable does not have any effect since it will always be overritten by that statement:

https://github.com/vedderb/bldc/blob/master/mc_interface.c#L1390

**Comment by vedderb** [comment]
Well spotted. I checked it a few times since I wrote this a while ago, but it is actually correct. Positive motor currents in this context correspond to acceleration currents in any direction and negative currents correspond to braking currents. Therefore the RPM limits are only applied to the maximum current while the temperature limits are applied to both currents as braking also heats up the motor. Depending on the direction the motor spins either one or the other RPM limit will end up being used. Also note that utils_min_abs will chose the value with the smallest magnitude, regardless of sign.
