### ISSUE TITLE
safe start bug? when exceeding the pulse width range, full throttle until return to neutral

### ISSUE THREAD

**Issue by erwincoumans** [vedderb/bldc#7]
reproduction:
choose PPM, enable safe start, duty cycle (for easier test on bench)
set the min pulse width and max pulse width a little bit so that the servo signal exceeds it
now exceed the 'max pulse width' by going full throttle, and then slowly release the throttle.

The signal stays full throttle, until returned to 'neutral' central position.

The workaround is to always make sure the servo never exceeds the min/max pulse width.
When disabling the 'safe start' this issue doesn't happen.

**Comment by vedderb** [comment]
This bug should only be present while BLDC Tool is connected. The reason for that is that BLDC Tool will prevent the timeout that stops the motor from occurring when the PPM signal is gone, which makes the motor run with the last set speed. When the servo signal comes back, safe start assumes that the motor isn't running and prevents all control commands before the neutral position has been active for 50 iterations.

This bug is now fixed in FW 1.4.

**Comment by erwincoumans** [comment]
thanks for the fix!
